site_name: PembrokePSalert
repo_url: https://github.com/jpsider/PembrokePSalert
theme: readthedocs
pages:
- Home: index.md
- PembrokePSalert Basics:
  - What is PembrokePSalert: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
