site_name: PembrokePSalert
repo_url: https://github.com/jpsider/PembrokePSalert
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- PembrokePSalert Basics:
  - What is PembrokePSalert: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Public Functions:
  - Invoke-DeployAlert: Invoke-DeployAlert.md
